routes:
  /:
    as: aardwolf.index
    uses: index
  /create:
    as: aardwolf.create
    uses: create
  post@/create:
    as: aardwolf.postCreate
    uses: postCreate
  /edit/{slug}:
    as: aardwolf.edit
    uses: edit
  post@/edit/{slug}:
    as: aardwolf.update
    uses: update
  /delete/{slug}:
    as: aardwolf.delete
    uses: delete

